# fly.toml app configuration file generated for notion-clone-server-side on 2024-06-11T19:43:41+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notion-clone-server-side'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3010
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
